### ISSUE TITLE
新学生wiki词条停止了

### ISSUE THREAD

**Issue by Aobaaaa** [luvsagiri/zhenxun_plugin_bawiki#1]
你好，用ba新学生指令，截下来的图显示，wiki那边有新的“当期UP”词条，原新学生词条停止维护了。
请问有其他办法能查看新的学生嘛
![S%0W@$5@AC416%_`KDWA}86](https://user-images.githubusercontent.com/106361074/195978617-6bfed13c-032f-4e65-8ff4-091e6206ee33.PNG)

**Comment by luvsagiri** [comment]
> 你好，用ba新学生指令，截下来的图显示，wiki那边有新的“当期UP”词条，原新学生词条停止维护了。 请问有其他办法能查看新的学生嘛 ![S%0W@$5@AC416%_`KDWA}86](https://user-images.githubusercontent.com/106361074/195978617-6bfed13c-032f-4e65-8ff4-091e6206ee33.PNG)

你好,nonebot使用元数据类型后,1.6.3版本后真寻可以直接使用nonebot插件,建议使用原版插件,地址https://github.com/lgc2333/nonebot-plugin-bawiki

**Comment by Aobaaaa** [comment]
> > 你好，用ba新学生指令，截下来的图显示，wiki那边有新的“当期UP”词条，原新学生词条停止维护了。 请问有其他办法能查看新的学生嘛 ![S%0W@$5@AC416%_`KDWA}86](https://user-images.githubusercontent.com/106361074/195978617-6bfed13c-032f-4e65-8ff4-091e6206ee33.PNG)
> 
> 你好,nonebot使用元数据类型后,1.6.3版本后真寻可以直接使用nonebot插件,建议使用原版插件,地址https://github.com/lgc2333/nonebot-plugin-bawiki

好的，感谢！
